GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/1

###

GET http://localhost:3001/api/persons/6

###

DELETE http://localhost:3001/api/persons/1

###

DELETE http://localhost:3001/api/persons/6

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Nuevo contacto 4",
    "number": "764-0194863"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "764-0194863"
}
###


